version: "3.8"

services:
  tv_backend:
    container_name: tv_backend
    user: 1000:1000 # for linux to delete created files--
    build:
      context: backend
      dockerfile: Dockerfile
    volumes:
      - /var/www/pl/video:/video
    command:
      [
        "uvicorn",
        "src.main:app",
        "--reload",
        "--host",
        "0.0.0.0",
        "--port",
        "8000"
      ]
    restart: unless-stopped
    ports:
      - '8100:8000'

  tv_frontend:
    container_name: tv_frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - '8180:8080'
    
